/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./navbar.html",
    "./footer.html",
    "./js/**/*.js",
    "./**/*.html",
    "./**/*.js",
  ],
  theme: {
    extend: {},
  },
  safelist: [
    'hidden',
    'flex',
    'block',
    'inline-block',
    'invisible',
    'active',
    'opacity-0',
    'opacity-50',
    'scale-95',
    'border-blue-500',
    'border-transparent',
    'border-slate-200',
    'border-emerald-500',
    'border-red-500',
    'text-blue-600',
    'text-blue-700',
    'text-emerald-500',
    'text-emerald-600',
    'text-emerald-700',
    'text-red-500',
    'text-red-600',
    'text-red-700',
    'text-slate-500',
    'text-slate-600',
    'text-slate-700',
    'text-slate-800',
    'text-slate-900',
    'bg-blue-50',
    'bg-blue-600',
    'bg-emerald-50',
    'bg-emerald-600',
    'bg-red-50',
    'bg-red-600',
    'bg-slate-50',
    'bg-slate-100',
    'animate-spin',
    'animate-pulse',
    'winner-glow',
    'loser-opacity'
  ],
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
